---
- name: Deploy Ubuntu VM on XCP-ng
  hosts: localhost
  # vars:
  #   xcpng_password: !vault |
  #         $ANSIBLE_VAULT;1.1;AES256
  #         38373430623531353639643535366638316235383035313531373961343064366464653863363637
  #         6363346433393239383233383664383662383439646632370a626436393062363634653032323565
  #         30393630313763663937386430613839383330323762343739323966316439623464643665633435
  #         3431346561326135380a376562626138386561646566616133633563306132376364343662656431
  #         33363534383033376437383139643231373534396237373365396435616231396633
  gather_facts: no
  tasks:
    - name: Generate random MAC address
      set_fact:
        random_mac: "{{ '00:16:3e' | community.general.random_mac }}"

    - name: Create VM
      community.general.xenserver_guest:
        hostname: 10.10.15.5
        username: root
        password: "{{ xcpng_password }}"
        validate_certs: false
        name: "{{ vm_name }}"
        state: poweredon
        template: "Ubuntu Jammy Jellyfish 22.04"
        disks:
          - size_gb: 40
            sr: VM-Pool
        hardware:
          num_cpus: 2
          num_cpu_cores_per_socket: 2
          memory_mb: 4096
        cdrom:
          type: iso
          iso_name: "ubuntu-22.04.3-live-server-amd64.iso"
        networks:
          - name: "Pool-wide network associated with eth0"
            mac: "{{ random_mac }}"
            ip: "{{ vm_ip }}"
            gateway: 10.10.15.1
      delegate_to: localhost
      register: deploy

    - name: Wait for VM
      ansible.builtin.wait_for:
        host: "{{ vm_ip }}"
        delay: 60
        timeout: 600
          
    - name: Add user
      ansible.builtin.user:
        name: "{{ vm_user }}"
        password: "{{ vm_password }}"
        shell: /bin/bash
        groups: sudo
        append: true
        state: present
        update_password: always
        generate_ssh_key: true
      delegate_to: "{{ vm_ip }}"
      # when: deploy.changed
        