---
- name: Deploy Ubuntu VM on XCP-ng
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Generate random MAC address
      set_fact:
        random_mac: "{{ '00:16:3e:%02x:%02x:%02x'|format(hostvars['localhost']['ansible_random']['int'] % 256, hostvars['localhost']['ansible_random']['int'] % 256, hostvars['localhost']['ansible_random']['int'] % 256) }}"

    - name: Create VM
      community.general.xenserver_guest:
        hostname: 10.10.15.5
        username: root
        password: "{{ xcpng_password }}"
        validate_certs: false
        name: "{{ vm_name }}"
        state: poweredon
        template: "Ubuntu Jammy Jellyfish 22.04"
        disks:
          - size_gb: 40
            sr: VM-Pool
        hardware:
          num_cpus: 2
          num_cpus_per_socket: 2
          memory_gb: 4
        cdrom:
          type: iso
          iso_name: "ubuntu-22.04.3-live-server-amd64.iso"
        networks:
          - network: "Pool-wide network associated with eth0"
            mac: "{{ random_mac }}"
            ip: "{{ vm_ip }}"
            gateway: 10.10.15.1
      delegate_to: localhost
      register: deploy

    - name: Wait for VM
      hosts: "{{ vm_ip }}"
        ansible.builtin.wait_for_connection:
          timeout: 600
          
    - name: Add user
      hosts: "{{ vm_ip }}"
      ansible.builtin.user:
        name: "{{ vm_user }}"
        password: "{{ vm_password }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
        update_password: always
        